INSERT INTO tb_category (name, created_At) VALUES ('Toys', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Clothing', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Sports', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Beauty', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Garden', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Home Decor', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Furniture', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Groceries', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Music', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Movies', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Jewelry', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Shoes', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Health', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Watches', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Office Supplies', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Tools', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Pets', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Baby Products', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Automotive', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Outdoors', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Video Games', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Photography', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Stationery', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Travel', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Luggage', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Fitness', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Crafts', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Musical Instruments', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Cleaning Supplies', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Board Games', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Smartphones', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Tablets', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Cameras', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Bookshelves', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Printers', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Monitors', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Kitchen Appliances', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Bicycles', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Drones', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Lighting', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Art Supplies', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Gaming Chairs', NOW());
